# Get base SDK image from Microsoft
FROM mcr.microsoft.com/dotnet/core/sdk/sdk:3.1 AS build-env
WORKDIR /app

# copy the CSPROJ file and restore any dependencies (via NUGET)
COPY *.csproj ./
RUN dotnet restore

# copy the project files and build release
COPY . ./
RUN dotnet publish -c Release -o out

#generate runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
EXPOSE 80
COPY --from=build-env /app/out .
ENTRYPOINT [ "dotnet", "WebApiTest.dll" ]